export { createProdutosRouter } from './productos.js';
export { createVentaRouter } from './venta.js';
export { createTallasRouter } from './tallas.js';
export { createInventarioRouter } from './inventario.js';
export { createTrabajadorRouter } from './trabajador.js';
export { createPedidoApartadoRouter } from './pedido_apartado.js';
export { createDetallePedidoApartadoRouter } from './detalle_pedido_apartado.js';
export { createUsuariosRouter } from './usuarios.js';
export { createDetalleVentaRouter } from './detalle_venta.js';
export { createTicketRouter } from './ticket.js';
export { createProductosTallasInventarioRouter } from './productos_tallas_inventario.js';
export { createCategoriasRouter } from './categorias.js';
export { createLoginUsuarioRouter } from './login_usuario.js';
export { createLoginTrabajadorRouter } from './login_trabajador.js';
export { createSimuladorRouter } from './simulador.js';
export { createEntregasRouter } from './entregas.js';
export { createBestSellersRouter} from './best_sellers.js'
export { createRecuperacionRouter } from './recuperacion.js';
export { createBestCategoriasRouter } from './best_categorias.js';